nodeLinker: node-modules
enableGlobalCache: true

logFilters:
  - code: YN0002 # Ignore "package.json" found with different casing warnings
    level: discard
  - code: YN0060 # Ignore "The package may be unstable" warnings
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
